### PR TITLE
some cumbat modules and player 

### PR DESCRIPTION
**Pull request by goztb22**
cumbat

### CODE REVIEW

**Comment by MOMIN5** [comment]
thanks, ill take a look

**Comment by ProfKambing** [comment]
this nigga just copy phobos 1.12 🤣 🤣 😂

**Comment by goztb22** [comment]
ofc ma friend im ultimate skid1!!!!!

**Comment by ghost** [comment]
jesus

**Comment by MOMIN5** [comment]
btw a LOT has changed in 1.16, so the mixins needs to rewritten, also phobos uses forge event system, which no longer exists cause fabric 1.16 so ye

**Pull request closed without merging**
